# Generated by Django 3.0.3 on 2020-02-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent', models.BooleanField(default=False)),
                ('retard', models.IntegerField(default=0)),
                ('justification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_promotion', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='null', max_length=10)),
                ('annee_filiere', models.CharField(default='2020-2021', max_length=10)),
                ('status_promotion', models.CharField(choices=[('cla', 'Classique'), ('app', 'Apprentissage'), ('mxt', 'Mixte')], default='Null', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateTimeField(null=True)),
                ('heure_deb', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeancePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(default='M2', on_delete=django.db.models.deletion.CASCADE, to='absence.Promotion')),
                ('seance_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Seance')),
            ],
        ),
        migrations.CreateModel(
            name='SeanceProfesseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur')),
                ('seance_professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Seance')),
            ],
        ),
        migrations.CreateModel(
            name='SeanceMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Matiere')),
                ('seance_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Seance')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionEtudiants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='MatierePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Matiere')),
                ('promotion_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='MatiereProfesseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Matiere')),
                ('professeur_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceSeance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Absence')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Seance')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceEtudiants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Absence')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur')),
            ],
        ),
    ]
