# Generated by Django 3.0.3 on 2020-02-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0002_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_promotion', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='null', max_length=2)),
                ('status_promotion', models.CharField(choices=[('cla', 'Licence 1'), ('app', 'Licence 2'), ('mxt', 'Licence 3')], default='Null', max_length=3)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateTimeField(null=True)),
                ('heure_deb', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Matiere')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Promotion')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Promotion'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent', models.BooleanField(default=False)),
                ('retard', models.IntegerField(default=0)),
                ('justification', models.CharField(max_length=255)),
                ('heure_deb', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.Seance')),
            ],
        ),
    ]
