# Generated by Django 3.0.3 on 2020-02-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='nom_promotion',
            field=models.CharField(choices=[('Licence 1', 'L1'), ('Licence 2', 'L2'), ('Licence 3', 'L3'), ('Master 1', 'M1'), ('Master 2', 'M2')], default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status_promotion',
            field=models.CharField(choices=[('Classique', 'CLA'), ('Apprentissage', 'APP'), ('Mixte', 'MXT')], default='Null', max_length=13),
        ),
    ]
