# Generated by Django 3.0.3 on 2020-02-19 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_auto_20200217_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date_seance',
            field=models.DateField(default=datetime.date(2020, 2, 19)),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_deb',
            field=models.TimeField(default='02:20'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(default='02:20'),
        ),
    ]
