# Generated by Django 3.0.3 on 2020-02-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_promotion_annee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='annee',
        ),
        migrations.AddField(
            model_name='promotion',
            name='annee_filiere',
            field=models.CharField(default='2019/2020', max_length=10),
        ),
    ]
