# Generated by Django 3.0.3 on 2020-02-19 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_auto_20200219_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date_seance',
            field=models.DateField(default=datetime.datetime(2020, 2, 19, 2, 24, 14, 715851, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_deb',
            field=models.TimeField(default='02:24'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(default='02:24'),
        ),
    ]
