# Generated by Django 3.0.3 on 2020-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_auto_20200207_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='annee_filiere',
            field=models.CharField(default='2020-2021', max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status_promotion',
            field=models.CharField(choices=[('cla', 'Classique'), ('app', 'Apprentissage'), ('mxt', 'Mixte')], default='Null', max_length=3),
        ),
    ]
